// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum ActionType {
  None,
  Idle,
  Dead,
  Mining,
  Shoveling,
  Stick,
  Fishing,
  Walking,
  Buy,
  Plant,
  Push,
  Chop,
  Teleport,
  Melee,
  Hop,
  Spawn,
  Bow
}

enum TerrainType {
  None,
  Rock,
  Mine,
  Tree,
  HeavyBoy,
  HeavyHeavyBoy,
  Pillar,
  Road,
  Hole,
  Miliarium
}

enum NPCType {
  None,
  Player,
  Soldier,
  Barbarian,
  Ox,
  BarbarianArcher
}

enum RoadState {
  None,
  Shoveled,
  Statumen,
  Rudus,
  Nucleas,
  Paved,
  Bones
}

enum RockType {
  None,
  Raw,
  Statumen,
  Pavimentum,
  Rudus,
  Nucleus,
  Miliarium,
  Heavy,
  HeavyHeavy,
  Pillar
}

enum MoveType {
  None,
  Obstruction,
  Hole,
  Carry,
  Push,
  Trap
}

enum FloraType {
  None,
  Tree,
  Oak,
  Bramble
}

enum PuzzleType {
  None,
  Miliarium,
  Bearer,
  Count
}

enum PaymentType {
  None,
  Coins,
  Gems,
  Eth
}
