// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Tester, TesterTableId } from "./tables/Tester.sol";
import { Balls, BallsTableId } from "./tables/Balls.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { AllTypes, AllTypesTableId } from "./tables/AllTypes.sol";
