// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAttackSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAttackSystem {
  function attack(int32 x, int32 y) external;
}
