/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace DefaultNamespace
{
    public class CounterTableUpdate : TypedRecordUpdate<Tuple<CounterTable?, CounterTable?>> { }

    public class CounterTable : IMudTable
    {
        public readonly static string ID = "Counter";
        public static RxTable CounterRxTable
        {
            get { return NetworkManager.Instance.ds.tableNameIndex[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public override Type TableType()
        {
            return typeof(CounterTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(CounterTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            CounterTable other = (CounterTable)obj;

            if (other == null)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters) { }

        public override void RecordToTable(RxRecord record)
        {
            var table = record.value;
            //bool hasValues = false;
        }
        
        public static Tuple<CounterTable?, CounterTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            CounterTable? current = null;
            CounterTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new CounterTable { };
                }
                catch (InvalidCastException)
                {
                    current = new CounterTable { };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new CounterTable { };
                }
                catch (InvalidCastException)
                {
                    previous = new CounterTable { };
                }
            }

            return new Tuple<CounterTable?, CounterTable?>(current, previous);
        }
    }
}
