// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISpawnSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISpawnSystem {
  function spawnPlayer() external;

  function spawnToad(int32 x, int32 y, int32 z) external;

  function deleteToad(int32 x, int32 y, int32 z) external;
}
