// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerTableId } from "./tables/Player.sol";
import { Toad, ToadTableId } from "./tables/Toad.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { GameManager, GameManagerTableId } from "./tables/GameManager.sol";
