/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using System.Linq;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class GameManagerTable : MUDTable
    {
        public class GameManagerTableUpdate : RecordUpdate
        {
            public uint? Tadpoles;
            public uint? PreviousTadpoles;
        }

        public readonly static string ID = "GameManager";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public uint? Tadpoles;

        public override Type TableType()
        {
            return typeof(GameManagerTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(GameManagerTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            GameManagerTable other = (GameManagerTable)obj;

            if (other == null)
            {
                return false;
            }
            if (Tadpoles != other.Tadpoles)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            Tadpoles = (uint)functionParameters[0];
        }

        public static IObservable<RecordUpdate> GetGameManagerTableUpdates()
        {
            GameManagerTable mudTable = new GameManagerTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            Tadpoles = (uint)property["tadpoles"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            uint? currentTadpolesTyped = null;
            uint? previousTadpolesTyped = null;

            if (currentValue != null && currentValue.ContainsKey("tadpoles"))
            {
                currentTadpolesTyped = (uint)currentValue["tadpoles"];
            }

            if (previousValue != null && previousValue.ContainsKey("tadpoles"))
            {
                previousTadpolesTyped = (uint)previousValue["tadpoles"];
            }

            return new GameManagerTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                Tadpoles = currentTadpolesTyped,
                PreviousTadpoles = previousTadpolesTyped,
            };
        }
    }
}
