// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Damage, DamageTableId } from "./tables/Damage.sol";
