/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class BallsTable : IMudTable
    {
        public class BallsTableUpdate : RecordUpdate
        {
            public int? Count;
            public int? PreviousCount;
        }

        public readonly static string ID = "Balls";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public int? Count;

        public override Type TableType()
        {
            return typeof(BallsTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(BallsTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            BallsTable other = (BallsTable)obj;

            if (other == null)
            {
                return false;
            }
            if (Count != other.Count)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            Count = (int)functionParameters[0];
        }

        public static IObservable<RecordUpdate> GetBallsTableUpdates()
        {
            BallsTable mudTable = new BallsTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            Count = (int)property["count"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            int? currentCountTyped = null;
            int? previousCountTyped = null;

            if (currentValue != null && currentValue.ContainsKey("count"))
            {
                currentCountTyped = (int)currentValue["count"];
            }

            if (previousValue != null && previousValue.ContainsKey("count"))
            {
                previousCountTyped = (int)currentValue["count"];
            }

            return new BallsTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                Count = currentCountTyped,
                PreviousCount = previousCountTyped,
            };
        }
    }
}
