/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class PositionTable : IMudTable
    {
        public class PositionTableUpdate : RecordUpdate
        {
            public string? key;
            public string? Previouskey;
            public int? x;
            public int? Previousx;
            public int? y;
            public int? Previousy;
            public int? layer;
            public int? Previouslayer;
        }

        public readonly static string ID = "Position";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public string? key;
        public int? x;
        public int? y;
        public int? layer;

        public override Type TableType()
        {
            return typeof(PositionTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(PositionTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            PositionTable other = (PositionTable)obj;

            if (other == null)
            {
                return false;
            }
            if (key != other.key)
            {
                return false;
            }
            if (x != other.x)
            {
                return false;
            }
            if (y != other.y)
            {
                return false;
            }
            if (layer != other.layer)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            key = (string)functionParameters[0];

            x = (int)functionParameters[1];

            y = (int)functionParameters[2];

            layer = (int)functionParameters[3];
        }

        public static IObservable<RecordUpdate> GetUpdates<T>()
            where T : IMudTable, new()
        {
            IMudTable mudTable = (IMudTable)Activator.CreateInstance(typeof(T));

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentValue as Property;
            var previousValue = recordUpdate.PreviousValue as Property;

            return new PositionTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentValue = recordUpdate.CurrentValue,
                PreviousValue = recordUpdate.PreviousValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                key = (string)(currentValue?["key"] ?? null),
                x = (int)(currentValue?["x"] ?? null),
                y = (int)(currentValue?["y"] ?? null),
                layer = (int)(currentValue?["layer"] ?? null),
                Previouskey = (string)(previousValue?["key"] ?? null),
                Previousx = (int)(previousValue?["x"] ?? null),
                Previousy = (int)(previousValue?["y"] ?? null),
                Previouslayer = (int)(previousValue?["layer"] ?? null),
            };
        }

        public override void RecordToTable(RxRecord record)
        {
            var table = record.RawValue;

            var keyValue = (string)table["key"];
            key = keyValue;
            var xValue = (int)table["x"];
            x = xValue;
            var yValue = (int)table["y"];
            y = yValue;
            var layerValue = (int)table["layer"];
            layer = layerValue;
        }
    }
}
