/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class RoadTable : IMudTable
    {
        public class RoadTableUpdate : RecordUpdate
        {
            public string? key;
            public string? Previouskey;
            public uint? state;
            public uint? Previousstate;
            public string? filled;
            public string? Previousfilled;
            public bool? gem;
            public bool? Previousgem;
        }

        public readonly static string ID = "Road";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public string? key;
        public uint? state;
        public string? filled;
        public bool? gem;

        public override Type TableType()
        {
            return typeof(RoadTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(RoadTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            RoadTable other = (RoadTable)obj;

            if (other == null)
            {
                return false;
            }
            if (key != other.key)
            {
                return false;
            }
            if (state != other.state)
            {
                return false;
            }
            if (filled != other.filled)
            {
                return false;
            }
            if (gem != other.gem)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            key = (string)functionParameters[0];

            state = (uint)functionParameters[1];

            filled = (string)functionParameters[2];

            gem = (bool)functionParameters[3];
        }

        public static IObservable<RecordUpdate> GetUpdates<T>()
            where T : IMudTable, new()
        {
            IMudTable mudTable = (IMudTable)Activator.CreateInstance(typeof(T));

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentValue as Property;
            var previousValue = recordUpdate.PreviousValue as Property;

            return new RoadTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentValue = recordUpdate.CurrentValue,
                PreviousValue = recordUpdate.PreviousValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                key = (string)(currentValue?["key"] ?? null),
                state = (uint)(int)(currentValue?["state"] ?? null),
                filled = (string)(currentValue?["filled"] ?? null),
                gem = (bool)(currentValue?["gem"] ?? null),
                Previouskey = (string)(previousValue?["key"] ?? null),
                Previousstate = (uint)(int)(previousValue?["state"] ?? null),
                Previousfilled = (string)(previousValue?["filled"] ?? null),
                Previousgem = (bool)(previousValue?["gem"] ?? null),
            };
        }

        public override void RecordToTable(RxRecord record)
        {
            var table = record.RawValue;

            var keyValue = (string)table["key"];
            key = keyValue;
            var stateValue = (uint)table["state"];
            state = stateValue;
            var filledValue = (string)table["filled"];
            filled = filledValue;
            var gemValue = (bool)table["gem"];
            gem = gemValue;
        }
    }
}
