// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITestSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITestSystem {
  function startTest() external;

  function updateAllBalls() external;

  function moveBall(bytes32 key) external;

  function spawnBall() external;
}
